"""
Interactive setup script for Morning-Brief.
Run once to create your .env file.
"""
import os
import sys


def ask(prompt, default=None, secret=False):
    if default:
        display = f"{prompt} [{default}]: "
    else:
        display = f"{prompt}: "

    if secret:
        import getpass
        value = getpass.getpass(display).strip()
    else:
        value = input(display).strip()

    if not value and default:
        return default
    return value


def main():
    print("\n=== Morning-Brief Setup ===\n")
    print("This will create your .env file. Press Enter to accept defaults.\n")

    env_path = os.path.join(os.path.dirname(__file__), ".env")
    if os.path.exists(env_path):
        overwrite = ask(".env already exists. Overwrite? (yes/no)", default="no")
        if overwrite.lower() not in ("yes", "y"):
            print("Aborted. Your existing .env was not changed.")
            sys.exit(0)

    print("\n--- Required: Anthropic ---")
    anthropic_key = ask("Anthropic API key (from console.anthropic.com)", secret=True)

    print("\n--- Required: Twilio ---")
    print("Find these at console.twilio.com under Account Info\n")
    twilio_sid = ask("Account SID (starts with AC)")
    twilio_token = ask("Auth Token", secret=True)
    twilio_from = ask("Your Twilio phone number (e.g. +15005551234)")
    twilio_to = ask("Your personal cell number to receive SMS (e.g. +12125551234)")

    print("\n--- Weather ---")
    weather_location = ask("Your city", default="New York,US")

    print("\n--- Market ---")
    watchlist = ask("Stock watchlist (comma-separated tickers)", default="AAPL,MSFT,NVDA")
    qqqm_top_n = ask("How many QQQM top holdings to show (1-10)", default="5")

    print("\n--- Personalization ---")
    name = ask("Your first name (optional, leave blank to skip)", default="")

    print("\n--- SMS length ---")
    print("160 = 1 SMS, 280 = 2 SMS, 1600 = up to 10 SMS")
    sms_chars = ask("Target SMS length in characters", default="280")

    lines = f"""# Morning-Brief Configuration — generated by setup.py

# --- REQUIRED ---
ANTHROPIC_API_KEY={anthropic_key}
TWILIO_ACCOUNT_SID={twilio_sid}
TWILIO_AUTH_TOKEN={twilio_token}
TWILIO_FROM_NUMBER={twilio_from}
TWILIO_TO_NUMBER={twilio_to}

# --- FEATURE FLAGS ---
ENABLE_WEATHER=true
ENABLE_NEWS=true
ENABLE_MARKET=true
ENABLE_CALENDAR=false
ENABLE_CUSTOM=false

# --- WEATHER ---
WEATHER_LOCATION={weather_location}
WEATHER_PROVIDER=wttr
OPENWEATHERMAP_API_KEY=

# --- NEWS ---
NEWS_FEEDS=https://feeds.bbci.co.uk/news/rss.xml,https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
NEWS_MAX_ITEMS_PER_FEED=5

# --- MARKET DATA ---
ENABLE_QQQM_HOLDINGS=true
QQQM_TOP_N={qqqm_top_n}
ENABLE_CRYPTO=true
STOCK_WATCHLIST={watchlist}

# --- GOOGLE CALENDAR (optional, disabled by default) ---
GOOGLE_CREDENTIALS_FILE=credentials/google_oauth_client.json
GOOGLE_TOKEN_FILE=credentials/token.json

# --- CUSTOM URLS ---
CUSTOM_URLS=

# --- CLAUDE TUNING ---
ANTHROPIC_MODEL=claude-haiku-4-5
SMS_TARGET_CHARS={sms_chars}
BRIEFING_STYLE=concise
RECIPIENT_NAME={name}
"""

    with open(env_path, "w") as f:
        f.write(lines)

    print(f"\n.env written to {env_path}")
    print("\nNext steps:")
    print("  python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt")
    print("  python main.py\n")


if __name__ == "__main__":
    main()
